FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache openssl

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci
RUN npx prisma generate

COPY . .

COPY docker-entrypoint.dev.sh ./docker-entrypoint.dev.sh
RUN chmod +x ./docker-entrypoint.dev.sh && mkdir -p uploads

EXPOSE 4000
ENTRYPOINT ["./docker-entrypoint.dev.sh"]
